export { default as HeroSection } from './HeroSection'
export { default as FeaturesSection } from './FeaturesSection'
export { default as CategoriesSection } from './CategoriesSection'
export { default as FeaturedProductsSection } from './FeaturedProductsSection'
export { default as NewsletterSection } from './NewsletterSection'
